AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for SelectFiDealerTrack

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  SelectFiDealerTrackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./src/SelectFiDealerTrack/
      Handler: SelectFiDealerTrack::SelectFiDealerTrack.Function::FunctionHandler
      Runtime: dotnet6
      Architectures:
        - x86_64
      MemorySize: 256
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        SelectFiDealerTrack:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /SelectFiDealerTrack
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SelectFiDealerTrackApi:
    Description: "API Gateway endpoint URL for Prod stage for SelectFiDealerTrack function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/SelectFiDealerTrack/"
  SelectFiDealerTrackFunction:
    Description: "SelectFiDealerTrack Lambda Function ARN"
    Value: !GetAtt SelectFiDealerTrackFunction.Arn
  SelectFiDealerTrackFunctionIamRole:
    Description: "Implicit IAM Role created for SelectFiDealerTrack function"
    Value: !GetAtt SelectFiDealerTrackFunctionRole.Arn
